qeman: setup cp: implement

diff --git a/qeman b/qeman
--- a/qeman
+++ b/qeman
@@ -79,6 +79,24 @@ setup_new() {
 
 }
 
+setup_cp() {
+	if [[ -z $1 || -z $2 ]]; then
+		echo "Not enough arguments"
+		exit 1
+	else
+		cfg_writer > $qeman_file
+		output=$(sed -n -e "/$1\]/,/^\[/{ /$1\]/d; /^\[/d; p; }" qeman.setups)
+		if [[ -z $output ]]; then
+			echo "Invalid source"
+			exit 1
+		fi
+		echo "Copying $1 to $2"
+		echo "[$2]" >> $qeman_file
+		echo "$output" >> $qeman_file
+		parse_config
+	fi
+}
+
 # Handling the mode commands
 if [ "$1" == mode ]; then
 	if [ "$2" == local ]; then
@@ -139,7 +157,7 @@ if [[ $1 == setup ]]; then
 	if [[ $2 == new ]]; then
 		setup_new $3
 	elif [[ $2 == cp ]]; then
-		echo 1
+		setup_cp $3 $4
 	elif [[ $2 == mv ]]; then
 		echo 1
 	elif [[ $2 == rm ]]; then
